# Generated by Django 3.2 on 2025-12-17 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_absence', '0002_auto_20251217_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_absence.class'),
        ),
    ]
